# Generated by Django 2.2.2 on 2019-06-08 16:59

from django.db import migrations, models
import imageupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=imageupload.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
