# Generated by Django 2.2.2 on 2019-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_scramble_image_name_20190608_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='thumbnail',
            field=models.ImageField(blank='True', upload_to='', verbose_name='Thumbnail of the uploaded image'),
        ),
    ]
