# Generated by Django 2.2.2 on 2019-06-10 03:56

from django.db import migrations, models
import imageupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_uploadimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='branch',
            field=models.TextField(choices=[('cse', 'CSE'), ('it', 'IT')], default='', max_length=100, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='emailid',
            field=models.TextField(default='', max_length=255, verbose_name='EmailId of the student'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='name',
            field=models.TextField(default='', max_length=255, verbose_name='Name of the student'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='number',
            field=models.TextField(default='', max_length=10, verbose_name='Contact number of the student'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='videofile',
            field=models.FileField(default='', upload_to=imageupload.models.scramble_uploaded_filename, verbose_name='Uploaded video'),
        ),
    ]
